name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
         java-version: ${{ matrix.java-version }}
      - name: Show java
        run: |
            echo $JAVA_HOME
            echo $PATH
            java -version
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build

      - name: Publish package
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SHAKY_ANDROID_GPG_PRIVATE_KEY: ${{ secrets.SHAKY_ANDROID_GPG_PRIVATE_KEY }}
          SHAKY_ANDROID_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.SHAKY_ANDROID_GPG_PRIVATE_KEY_PASSWORD }}
